# 큰 DataFrame 살펴보기

In [3]:
import pandas as pd
df = pd.read_csv('C:/codeit/laptops.csv')
df.head()

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
0,Dell,Inspiron 15-3567,4,hdd,1024,15.6,40000,intel,i5,2.5,intel,NaN,linux,2.50,NaN
1,Apple,MacBook Air,8,ssd,128,13.3,55499,intel,i5,1.8,intel,2.0,mac,1.35,NaN
2,Apple,MacBook Air,8,ssd,256,13.3,71500,intel,i5,1.8,intel,2.0,mac,1.35,NaN
3,Apple,MacBook Pro,8,ssd,128,13.3,96890,intel,i5,2.3,intel,2.0,mac,3.02,NaN
4,Apple,MacBook Pro,8,ssd,256,13.3,112666,intel,i5,2.3,intel,2.0,mac,3.02,NaN

In [4]:
df.shape

(167, 15)

In [5]:
df.columns
#어떤 컬럼이 있는지 확인 가능

Index(['brand', 'model', 'ram', 'hd_type', 'hd_size', 'screen_size', 'price',
       'processor_brand', 'processor_model', 'clock_speed',
       'graphic_card_brand', 'graphic_card_size', 'os', 'weight', 'comments'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 15 columns):
brand                 167 non-null object
model                 167 non-null object
ram                   167 non-null int64
hd_type               167 non-null object
hd_size               167 non-null int64
screen_size           167 non-null float64
price                 167 non-null int64
processor_brand       167 non-null object
processor_model       167 non-null object
clock_speed           166 non-null float64
graphic_card_brand    163 non-null object
graphic_card_size     81 non-null float64
os                    167 non-null object
weight                160 non-null float64
comments              55 non-null object
dtypes: float64(4), int64(3), object(8)
memory usage: 19.6+ KB

In [7]:
df.describe()
# 컬럼의통계값 출력

,ram,hd_size,screen_size,price,clock_speed,graphic_card_size,weight
count,167.000000,167.00000,167.000000,167.000000,166.000000,81.000000,160.000000
mean,6.898204,768.91018,14.775210,64132.898204,2.321084,52.160494,2.250812
std,3.787479,392.99080,1.376526,42797.674010,0.554187,444.134142,0.648446
min,2.000000,32.00000,10.100000,13872.000000,1.100000,1.000000,0.780000
25%,4.000000,500.00000,14.000000,35457.500000,1.900000,2.000000,1.900000
50%,8.000000,1024.00000,15.600000,47990.000000,2.300000,2.000000,2.200000
75%,8.000000,1024.00000,15.600000,77494.500000,2.600000,4.000000,2.600000
max,16.000000,2048.00000,17.600000,226000.000000,3.800000,4000.000000,4.200000

In [8]:
df.sort_values(by = 'price')

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
148,Acer,Aspire SW3-016,2,ssd,32,10.1,13872,intel,Atom Z8300,1.44,intel,NaN,windows,1.20,NaN
83,Acer,A315-31CDC UN.GNTSI.001,2,ssd,500,15.6,17990,intel,Celeron,1.10,intel,NaN,windows,2.10,NaN
108,Acer,Aspire ES-15 NX.GKYSI.010,4,hdd,500,15.6,17990,amd,A4-7210,1.80,amd,NaN,windows,2.40,NaN
100,Acer,A315-31-P4CRUN.GNTSI.002,4,hdd,500,15.6,18990,intel,pentium,1.10,intel,NaN,windows,NaN,NaN
73,Acer,Aspire ES1-523,4,hdd,1024,15.6,19465,amd,A4-7210,1.80,amd,NaN,linux,2.40,NaN
143,Acer,Aspire ES 15,4,hdd,1024,15.6,19589,amd,E1-7010,1.50,amd,NaN,linux,2.40,NaN
158,Asus,X540YA-XO290D,4,hdd,1024,15.6,19990,amd,APU Quad Core E2,1.80,amd,NaN,linux,2.00,NaN
14,Dell,Inspiron 15 3565,4,hdd,500,15.0,20990,amd,E2,1.80,amd,NaN,linux,2.30,Integrated Graphics
9,Dell,Inspiron 15.6 3552,4,hdd,500,15.0,21990,intel,pentium N3710,1.60,intel,NaN,linux,2.19,Integrated Graphics
119,HP,"245 G4,P1b38PA",4,ssd,1024,15.6,21999,amd,E2-7110,1.80,amd,NaN,linux,2.93,NaN
159,Asus,P2420SA,4,hdd,500,14.0,22290,intel,Pentium Quad Core,1.60,intel,NaN,linux,1.95,NaN
121,Dell,Inspiron 15 3551,2,hdd,500,15.6,23000,intel,Pentium,2.16,intel,NaN,linux,3.12,Integrated graphics
137,HP,15-bg007AU,4,ssd,500,15.6,23990,amd,A6-7310,2.00,amd,NaN,windows,2.50,NaN
123,HP,15-ac118tu,4,ssd,500,15.6,23990,intel,Pentium N3825U,1.90,intel,NaN,linux,3.03,Intel Integrated Graphics
115,Acer,Aspire Es1-572-38Cy,4,hdd,1024,15.6,24890,intel,i3,2.30,intel,NaN,linux,3.36,NaN
13,Dell,Vostro 3568,4,hdd,500,15.6,24900,intel,Celeron 3855U,1.60,intel,NaN,linux,2.50,Integrated Graphics
117,Acer,A315-21G NX.GNPSI.002,4,hdd,500,15.6,24990,intel,i3,2.00,intel,NaN,linux,2.10,NaN
132,HP,15-BE002TU,4,hdd,1024,15.6,25248,intel,Pentium N3710,1.60,intel,NaN,linux,2.19,NaN
21,Dell,Inspiron 11 3148,4,hdd,500,11.6,25990,intel,i3,1.90,intel,NaN,windows,1.40,integrated Graphics
129,HP,15- BS547TU,4,ssd,500,15.6,26299,intel,Pentium N3710,1.60,NaN,NaN,windows,2.10,Integrated Graphics
112,Acer,Aspire R3-131T,4,hdd,500,11.6,26490,intel,Pentium N3700,1.60,intel,NaN,windows,1.58,NaN
160,Asus,X540LA-XX596D,4,hdd,1024,15.6,26990,intel,i3 5th gen,2.00,intel,NaN,linux,1.90,NaN
127,Acer,Aspire R3-131T 2017,4,hdd,500,11.6,27199,intel,Pentium N3710,1.60,intel,NaN,windows,2.40,NaN
139,Acer,ASPIRE E5-575,4,hdd,1024,15.6,27280,intel,i3,2.30,NaN,2.0,linux,NaN,NaN
161,Asus,X541UA-GO1345D,4,hdd,1024,15.6,27730,intel,i3 6th gen,2.00,intel,NaN,linux,1.84,NaN
50,HP,15q-bu004tu,4,hdd,1024,15.6,27990,intel,i3,2.00,intel,NaN,linux,2.10,NaN
163,Asus,X555LA-XX172D,4,hdd,500,15.6,28489,intel,i3 4th gen,1.90,intel,NaN,linux,2.30,NaN
125,HP,15-AY542TU,4,hdd,1024,15.6,28590,intel,i3,2.00,intel,NaN,linux,2.19,NaN
16,Dell,Latitude 3480,4,hdd,500,14.0,28870,intel,i3,2.00,intel,NaN,linux,1.80,Integrated Graphics
164,Asus,X554LD,2,hdd,500,15.6,29199,intel,i3 4th gen,1.90,intel,1.0,linux,2.30,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,Apple,MacBook,8,ssd,256,12.0,96990,intel,core m,1.20,intel,2.0,mac,0.92,NaN
60,Dell,Inspiron 15 7000 7567,16,ssd,128,15.6,99991,intel,i7,2.80,nvidia,4.0,windows,2.80,NaN
105,Dell,XPS 12 Ultrabook,4,ssd,128,12.0,101065,intel,i5,2.60,intel,NaN,windows,3.20,Average Battery Life (in hours): 4 Lithium Bat...
15,Acer,Predator Helios 300,16,ssd,1024,15.6,101839,intel,i7,2.80,nvidia,6.0,windows,2.70,Gaming Laptop
38,HP,13-D115TU,8,ssd,256,13.3,101882,intel,i7,2.50,intel,1.0,windows,NaN,NaN
30,Acer,ASPIRE V NITRO,12,hdd,1024,15.6,105300,intel,i7,2.60,nvidia,4.0,windows,2.40,NaN
32,Acer,Aspire-V VN7-591G,12,hdd,1024,15.6,105510,intel,i7,2.60,nvidia,1.0,windows,2.40,NaN
4,Apple,MacBook Pro,8,ssd,256,13.3,112666,intel,i5,2.30,intel,2.0,mac,3.02,NaN
98,Dell,Inspiron 15 Gaming 7567,16,hdd,1280,15.6,112990,intel,i7,3.80,nvidia,4.0,windows,2.80,Operating System: Windows 10 with Office 201...
41,HP,13-ac058TU,8,ssd,360,13.3,115290,intel,i5,2.50,intel,NaN,windows,1.32,NaN
118,Alienware,13 Y560901IN9,8,hdd,1024,13.0,117299,intel,i5,2.70,nvidia,2.0,windows,2.50,NaN
82,Dell,Inspiron 17 7567,16,ssd,256,15.6,119780,intel,i7,2.80,NaN,NaN,windows,4.10,NaN
149,Microsoft,Surface Pro 4 CQ9-00016,8,ssd,256,12.3,122990,intel,i7,1.80,intel,NaN,windows,0.79,Laptop/Tablet: Go from tablet to laptop in a s...
26,Acer,Spin 7 SP714-51,8,hdd,256,14.0,124900,intel,i7,3.60,intel,NaN,windows,1.20,Integrated Graphics
64,Acer,Nitro 5,16,ssd,256,14.0,131551,intel,i5,3.50,nvidia,4.0,windows,2.70,NaN
153,Microsoft,Surface Book CR9-00001,8,ssd,128,13.5,143857,intel,i5,1.80,intel,NaN,windows,1.60,NaN
36,HP,Omen 15-ce074tx,16,ssd,128,15.6,143990,intel,i7,2.80,nvidia,6.0,windows,2.60,Windows 10 Home
47,HP,13-v122TU,8,ssd,512,13.3,143999,intel,i7,2.70,intel,NaN,windows,1.11,NaN
130,Alienware,17R3 1471045648,8,hdd,1024,17.3,150453,intel,i7,2.60,nvidia,3.0,windows,3.80,NaN
116,Alienware,OEM,16,hdd,1024,15.6,151258,intel,i7,2.60,nvidia,4.0,windows,3.18,"Display: 15.6"" in 4K UHD IPS touchscreen (3840..."
6,Apple,MacBook Pro (TouchBar),16,ssd,512,13.3,158000,intel,i5,2.90,intel,2.0,mac,1.37,NaN
44,HP,13-ac059TU,16,ssd,512,13.3,169280,intel,i7,2.70,intel,NaN,windows,NaN,NaN
34,HP,Omen W 250TX,16,ssd,256,17.6,169990,intel,i7,3.60,nvidia,8.0,windows,2.70,The Best Gaming is on GeForce Discover desktop...
151,Microsoft,Surface Laptop DAG-00001,8,ssd,256,13.5,171901,intel,i5,1.80,intel,NaN,windows,1.20,Integrated Graphics
122,Alienware,ANW17-2143SLV,8,hdd,1024,17.3,178427,intel,i7,2.50,nvidia,3.0,windows,3.80,17.3 inch FHD (1920 x 1080) IPS-Panel Anti-Gla...
154,Microsoft,Surface Book CR9-00013,8,ssd,128,13.5,178799,intel,i5,1.80,intel,NaN,windows,1.50,NaN
31,Acer,Predator 17,16,ssd,256,17.3,178912,intel,i7,2.60,nvidia,NaN,windows,4.20,Integrated Graphics
96,Alienware,AW13R3-7000SLV-PUS,8,ssd,256,13.3,190256,intel,i7,3.00,nvidia,6.0,windows,2.60,13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
90,Alienware,15 Notebook,16,hdd,1024,15.6,199000,intel,i7,2.60,nvidia,8.0,windows,3.50,Maximum Display Resolution : 1920 x 1080 pixel
5,Apple,MacBook Pro (TouchBar),16,ssd,512,15.0,226000,intel,i7,2.70,intel,2.0,mac,2.50,NaN

In [9]:
df.sort_values(by = 'price', ascending = False)

,brand,model,ram,hd_type,hd_size,screen_size,price,processor_brand,processor_model,clock_speed,graphic_card_brand,graphic_card_size,os,weight,comments
5,Apple,MacBook Pro (TouchBar),16,ssd,512,15.0,226000,intel,i7,2.70,intel,2.0,mac,2.50,NaN
90,Alienware,15 Notebook,16,hdd,1024,15.6,199000,intel,i7,2.60,nvidia,8.0,windows,3.50,Maximum Display Resolution : 1920 x 1080 pixel
96,Alienware,AW13R3-7000SLV-PUS,8,ssd,256,13.3,190256,intel,i7,3.00,nvidia,6.0,windows,2.60,13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...
31,Acer,Predator 17,16,ssd,256,17.3,178912,intel,i7,2.60,nvidia,NaN,windows,4.20,Integrated Graphics
154,Microsoft,Surface Book CR9-00013,8,ssd,128,13.5,178799,intel,i5,1.80,intel,NaN,windows,1.50,NaN
122,Alienware,ANW17-2143SLV,8,hdd,1024,17.3,178427,intel,i7,2.50,nvidia,3.0,windows,3.80,17.3 inch FHD (1920 x 1080) IPS-Panel Anti-Gla...
151,Microsoft,Surface Laptop DAG-00001,8,ssd,256,13.5,171901,intel,i5,1.80,intel,NaN,windows,1.20,Integrated Graphics
34,HP,Omen W 250TX,16,ssd,256,17.6,169990,intel,i7,3.60,nvidia,8.0,windows,2.70,The Best Gaming is on GeForce Discover desktop...
44,HP,13-ac059TU,16,ssd,512,13.3,169280,intel,i7,2.70,intel,NaN,windows,NaN,NaN
6,Apple,MacBook Pro (TouchBar),16,ssd,512,13.3,158000,intel,i5,2.90,intel,2.0,mac,1.37,NaN
116,Alienware,OEM,16,hdd,1024,15.6,151258,intel,i7,2.60,nvidia,4.0,windows,3.18,"Display: 15.6"" in 4K UHD IPS touchscreen (3840..."
130,Alienware,17R3 1471045648,8,hdd,1024,17.3,150453,intel,i7,2.60,nvidia,3.0,windows,3.80,NaN
47,HP,13-v122TU,8,ssd,512,13.3,143999,intel,i7,2.70,intel,NaN,windows,1.11,NaN
36,HP,Omen 15-ce074tx,16,ssd,128,15.6,143990,intel,i7,2.80,nvidia,6.0,windows,2.60,Windows 10 Home
153,Microsoft,Surface Book CR9-00001,8,ssd,128,13.5,143857,intel,i5,1.80,intel,NaN,windows,1.60,NaN
64,Acer,Nitro 5,16,ssd,256,14.0,131551,intel,i5,3.50,nvidia,4.0,windows,2.70,NaN
26,Acer,Spin 7 SP714-51,8,hdd,256,14.0,124900,intel,i7,3.60,intel,NaN,windows,1.20,Integrated Graphics
149,Microsoft,Surface Pro 4 CQ9-00016,8,ssd,256,12.3,122990,intel,i7,1.80,intel,NaN,windows,0.79,Laptop/Tablet: Go from tablet to laptop in a s...
82,Dell,Inspiron 17 7567,16,ssd,256,15.6,119780,intel,i7,2.80,NaN,NaN,windows,4.10,NaN
118,Alienware,13 Y560901IN9,8,hdd,1024,13.0,117299,intel,i5,2.70,nvidia,2.0,windows,2.50,NaN
41,HP,13-ac058TU,8,ssd,360,13.3,115290,intel,i5,2.50,intel,NaN,windows,1.32,NaN
98,Dell,Inspiron 15 Gaming 7567,16,hdd,1280,15.6,112990,intel,i7,3.80,nvidia,4.0,windows,2.80,Operating System: Windows 10 with Office 201...
4,Apple,MacBook Pro,8,ssd,256,13.3,112666,intel,i5,2.30,intel,2.0,mac,3.02,NaN
32,Acer,Aspire-V VN7-591G,12,hdd,1024,15.6,105510,intel,i7,2.60,nvidia,1.0,windows,2.40,NaN
30,Acer,ASPIRE V NITRO,12,hdd,1024,15.6,105300,intel,i7,2.60,nvidia,4.0,windows,2.40,NaN
38,HP,13-D115TU,8,ssd,256,13.3,101882,intel,i7,2.50,intel,1.0,windows,NaN,NaN
15,Acer,Predator Helios 300,16,ssd,1024,15.6,101839,intel,i7,2.80,nvidia,6.0,windows,2.70,Gaming Laptop
105,Dell,XPS 12 Ultrabook,4,ssd,128,12.0,101065,intel,i5,2.60,intel,NaN,windows,3.20,Average Battery Life (in hours): 4 Lithium Bat...
60,Dell,Inspiron 15 7000 7567,16,ssd,128,15.6,99991,intel,i7,2.80,nvidia,4.0,windows,2.80,NaN
7,Apple,MacBook,8,ssd,256,12.0,96990,intel,core m,1.20,intel,2.0,mac,0.92,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164,Asus,X554LD,2,hdd,500,15.6,29199,intel,i3 4th gen,1.90,intel,1.0,linux,2.30,NaN
16,Dell,Latitude 3480,4,hdd,500,14.0,28870,intel,i3,2.00,intel,NaN,linux,1.80,Integrated Graphics
125,HP,15-AY542TU,4,hdd,1024,15.6,28590,intel,i3,2.00,intel,NaN,linux,2.19,NaN
163,Asus,X555LA-XX172D,4,hdd,500,15.6,28489,intel,i3 4th gen,1.90,intel,NaN,linux,2.30,NaN
50,HP,15q-bu004tu,4,hdd,1024,15.6,27990,intel,i3,2.00,intel,NaN,linux,2.10,NaN
161,Asus,X541UA-GO1345D,4,hdd,1024,15.6,27730,intel,i3 6th gen,2.00,intel,NaN,linux,1.84,NaN
139,Acer,ASPIRE E5-575,4,hdd,1024,15.6,27280,intel,i3,2.30,NaN,2.0,linux,NaN,NaN
127,Acer,Aspire R3-131T 2017,4,hdd,500,11.6,27199,intel,Pentium N3710,1.60,intel,NaN,windows,2.40,NaN
160,Asus,X540LA-XX596D,4,hdd,1024,15.6,26990,intel,i3 5th gen,2.00,intel,NaN,linux,1.90,NaN
112,Acer,Aspire R3-131T,4,hdd,500,11.6,26490,intel,Pentium N3700,1.60,intel,NaN,windows,1.58,NaN
129,HP,15- BS547TU,4,ssd,500,15.6,26299,intel,Pentium N3710,1.60,NaN,NaN,windows,2.10,Integrated Graphics
21,Dell,Inspiron 11 3148,4,hdd,500,11.6,25990,intel,i3,1.90,intel,NaN,windows,1.40,integrated Graphics
132,HP,15-BE002TU,4,hdd,1024,15.6,25248,intel,Pentium N3710,1.60,intel,NaN,linux,2.19,NaN
117,Acer,A315-21G NX.GNPSI.002,4,hdd,500,15.6,24990,intel,i3,2.00,intel,NaN,linux,2.10,NaN
13,Dell,Vostro 3568,4,hdd,500,15.6,24900,intel,Celeron 3855U,1.60,intel,NaN,linux,2.50,Integrated Graphics
115,Acer,Aspire Es1-572-38Cy,4,hdd,1024,15.6,24890,intel,i3,2.30,intel,NaN,linux,3.36,NaN
137,HP,15-bg007AU,4,ssd,500,15.6,23990,amd,A6-7310,2.00,amd,NaN,windows,2.50,NaN
123,HP,15-ac118tu,4,ssd,500,15.6,23990,intel,Pentium N3825U,1.90,intel,NaN,linux,3.03,Intel Integrated Graphics
121,Dell,Inspiron 15 3551,2,hdd,500,15.6,23000,intel,Pentium,2.16,intel,NaN,linux,3.12,Integrated graphics
159,Asus,P2420SA,4,hdd,500,14.0,22290,intel,Pentium Quad Core,1.60,intel,NaN,linux,1.95,NaN
119,HP,"245 G4,P1b38PA",4,ssd,1024,15.6,21999,amd,E2-7110,1.80,amd,NaN,linux,2.93,NaN
9,Dell,Inspiron 15.6 3552,4,hdd,500,15.0,21990,intel,pentium N3710,1.60,intel,NaN,linux,2.19,Integrated Graphics
14,Dell,Inspiron 15 3565,4,hdd,500,15.0,20990,amd,E2,1.80,amd,NaN,linux,2.30,Integrated Graphics
158,Asus,X540YA-XO290D,4,hdd,1024,15.6,19990,amd,APU Quad Core E2,1.80,amd,NaN,linux,2.00,NaN
143,Acer,Aspire ES 15,4,hdd,1024,15.6,19589,amd,E1-7010,1.50,amd,NaN,linux,2.40,NaN
73,Acer,Aspire ES1-523,4,hdd,1024,15.6,19465,amd,A4-7210,1.80,amd,NaN,linux,2.40,NaN
100,Acer,A315-31-P4CRUN.GNTSI.002,4,hdd,500,15.6,18990,intel,pentium,1.10,intel,NaN,windows,NaN,NaN
108,Acer,Aspire ES-15 NX.GKYSI.010,4,hdd,500,15.6,17990,amd,A4-7210,1.80,amd,NaN,windows,2.40,NaN
83,Acer,A315-31CDC UN.GNTSI.001,2,ssd,500,15.6,17990,intel,Celeron,1.10,intel,NaN,windows,2.10,NaN
148,Acer,Aspire SW3-016,2,ssd,32,10.1,13872,intel,Atom Z8300,1.44,intel,NaN,windows,1.20,NaN

# 큰 Series 살펴보기

In [10]:
df = pd.read_csv('C:/codeit/laptops.csv')

In [11]:
df['brand']
# 밑에 lenth에서 자료가 몇개 있는지 파악 가능

0           Dell
1          Apple
2          Apple
3          Apple
4          Apple
5          Apple
6          Apple
7          Apple
8           Dell
9           Dell
10          Dell
11          Dell
12          Dell
13          Dell
14          Dell
15          Acer
16          Dell
17          Acer
18          Dell
19          Acer
20          Acer
21          Dell
22          Acer
23          Dell
24          Acer
25          Dell
26          Acer
27          Acer
28          Acer
29          Acer
         ...
137           HP
138           HP
139         Acer
140           HP
141           HP
142           HP
143         Acer
144    Microsoft
145           HP
146           HP
147    Microsoft
148         Acer
149    Microsoft
150           HP
151    Microsoft
152           HP
153    Microsoft
154    Microsoft
155       Lenovo
156       Lenovo
157       Lenovo
158         Asus
159         Asus
160         Asus
161         Asus
162         Asus
163         Asus
164         Asus
165         Asus
166         Asus
Name: brand, Length: 167, dtype: object

In [12]:
df['brand'].unique()

array(['Dell', 'Apple', 'Acer', 'HP', 'Lenovo', 'Alienware', 'Microsoft',
       'Asus'], dtype=object)

In [13]:
df['brand'].value_counts()

HP           55
Acer         35
Dell         31
Lenovo       18
Asus          9
Apple         7
Alienware     6
Microsoft     6
Name: brand, dtype: int64

In [14]:
df['brand'].describe()

count     167
unique      8
top        HP
freq       55
Name: brand, dtype: object

# Q. 여행지 선정하기 pt.1
### 1. 도시와 국가 수 구하기

In [15]:
df = pd.read_csv('C:/codeit/world_cities.csv', index_col = 0)
df['Country'].describe() # 61
df['City / Urban area'].describe() # 249

count        249
unique       249
top       Boston
freq           1
Name: City / Urban area, dtype: object

### 2. 인구 밀도 10000 넘는 도시 몇개?

In [16]:
#df['Population']/df['Land area(in sqKm)']
df['Density'] = (df['Population'] / df['Land area (in sqKm)'])
over10000 = df['Density'] > 10000
df[over10000].shape

(19, 5)

### 3. 인구밀도가 가장 높은 도시 이름은?

In [17]:
density_ranks = df.sort_values(by = 'Density', ascending = False)
density_ranks.head()

    City / Urban area   Country  Population  Land area (in sqKm)       Density
75             Mumbai     India    14350000                  484  29648.760331
74            Kolkata     India    12700000                  531  23917.137476
101           Karachi  Pakistan     9800000                  518  18918.918919
99              Lagos   Nigeria    13400000                  738  18157.181572
34           Shenzhen     China     8000000                  466  17167.381974

In [18]:
df.loc[0]

City / Urban area      Buenos Aires
Country                   Argentina
Population                 11200000
Land area (in sqKm)            2266
Density                     4942.63
Name: 0, dtype: object

# Q. 여행지 선정하기 pt.2

1. 이 데이터에 4개의 도시가 나왔다. 어느 나라인가?

In [19]:
#df['City / Urban area']
countries = df['Country'].value_counts()

countries[countries == 4]

# Oh... 지정된 값을 넣어 원하는 데이터 출력하기

Italy    4
Name: Country, dtype: int64

# Q. 수강신청 준비하기

1. information technology 과목은 1학년 수강 불가
2. commerce 과목은 4학년 수강 불가
3. 수강생이 5명 이하이면 폐강
4. 'stauts' column추가, 수강가능하면 'allowed', 불가하면 'not allowed'

In [20]:
df = pd.read_csv("C:/codeit/enrolment_1.csv")
df.head(10)

        id  year    course name
0  2777729     1        science
1  2777730     2        science
2  2777765     1           arts
3  2777766     2           arts
4  2777785     1            mba
5  2777786     2            mba
6  2777793     1  mba 2nd shift
7  2777794     2  mba 2nd shift
8  2777795     1  mca 2nd shift
9  2777796     2  mca 2nd shift

In [21]:
# 1번 조건
df['status'] = 'allowed'
df.loc[(df['course name'] == 'information technology')&(df['year']==1), 'status'] = 'not allowed'

In [22]:
# 2번 조건
df.loc[(df['year']==4) & (df['course name']=='commerce'), 'status'] = 'not allowed'

In [23]:
# under5 = (df['course name'].value_counts() < 5)
# df.loc[under5, 'status'] = 'not allowed'

# 또 오류

In [24]:
# counts = df['course name'].value_counts()
# df.loc[df[counts < 5], 'stauts'] = 'not allowed'

# 마이 오답

In [25]:
# 3번 조건
counts = df.loc[df['status']=='allowed','course name'].value_counts() < 5
closed_courses = list(counts[counts].index)
for course in closed_courses:
    df.loc[df['course name'] == course, 'status'] = 'not allowed'

# 요게 어렵네

# Q. 강의실 배정하기 pt.1

In [103]:
df = pd.read_csv('C:/codeit/enrolment_2.csv')

df['room assignment'] = 'not assigned'


allowed = df['status'] == 'allowed'
course_count = df.loc[allowed, 'course name'].value_counts()
# df 문에 조건 넣을 땐, 무조건 .loc 달아줘야 한다.


aud = list(course_count[course_count >= 80].index)
lar  = list(course_count[(80 > course_count)&(course_count >= 40)].index)
medi = list(course_count[(40 > course_count)&(course_count >= 15)].index)
small = list(course_count[(15 > course_count)&(course_count >= 5)].index)



for course in aud:
    df.loc[(df['course name']==course) & allowed, 'room assignment'] = 'Auditorium'

for course in lar:
    df.loc[(df['course name']==course) & allowed, 'room assignment'] = 'Large room'

for course in medi:
    df.loc[(df['course name']==course) & allowed, 'room assignment'] = 'Medium room'

for course in small:
    df.loc[(df['course name']==course) & allowed, 'room assignment'] = 'Small room'

df
    
# 포문을 돌려서, 나오는 인덱스가 aud에 속하면, room assignment 에 auditorium을 할당

           id  year           course name       status room assignment
0     2777729     1               science      allowed      Auditorium
1     2777730     2               science      allowed      Auditorium
2     2777765     1                  arts      allowed      Auditorium
3     2777766     2                  arts      allowed      Auditorium
4     2777785     1                   mba      allowed      Small room
5     2777786     2                   mba      allowed      Small room
6     2777793     1         mba 2nd shift  not allowed    not assigned
7     2777794     2         mba 2nd shift  not allowed    not assigned
8     2777795     1         mca 2nd shift  not allowed    not assigned
9     2777796     2         mca 2nd shift  not allowed    not assigned
10    2777797     3         mca 2nd shift  not allowed    not assigned
11    2777798     1                  bjmc  not allowed    not assigned
12    2777799     2                  bjmc  not allowed    not assigned
13    2777800     3                  bjmc  not allowed    not assigned
14    2777814     1               history      allowed     Medium room
15    2777815     2               history      allowed     Medium room
16    2777837     4             chemistry      allowed     Medium room
17    2777858     4                botany      allowed     Medium room
18    2604364     1               history      allowed     Medium room
19    2604408     3               finance      allowed      Small room
20    2604407     2               finance      allowed      Small room
21    2604420     1               physics      allowed     Medium room
22    2777899     1      computer science      allowed     Medium room
23    2604365     2               history      allowed     Medium room
24    2604413     2               english      allowed      Large room
25    2604406     1               finance      allowed      Small room
26    2604366     3               history      allowed     Medium room
27    2604412     1               english      allowed      Large room
28    2604421     2               physics      allowed     Medium room
29    2777900     4              commerce  not allowed    not assigned
...       ...   ...                   ...          ...             ...
1970  2796702     1      computer science      allowed     Medium room
1971  2796703     2      computer science      allowed     Medium room
1972  2796704     3      computer science      allowed     Medium room
1973  2796756     1             education      allowed      Large room
1974  2796757     2             education      allowed      Large room
1975  2796769     1            management      allowed     Medium room
1976  2796770     2            management      allowed     Medium room
1977  2796771     3            management      allowed     Medium room
1978  2796772     1           music vocal  not allowed    not assigned
1979  2796773     2           music vocal  not allowed    not assigned
1980  2796774     3           music vocal  not allowed    not assigned
1981  2796783     1     political science      allowed      Small room
1982  2796784     2     political science      allowed      Small room
1983  2796785     3     political science      allowed      Small room
1984  2796786     1        computers (ug)  not allowed    not assigned
1985  2796787     2        computers (ug)  not allowed    not assigned
1986  2796788     3        computers (ug)  not allowed    not assigned
1987  2796789     1             economics      allowed     Medium room
1988  2796790     2             economics      allowed     Medium room
1989  2796791     3             economics      allowed     Medium room
1990  2796800     1                 hindi      allowed      Small room
1991  2796801     2                 hindi      allowed      Small room
1992  2796802     3                 hindi      allowed      Small room
1993  2796803     1  computer application      allowed     Medium room
1994  2796804     2  computer application      allowed     Medium room
1995  2796805     3  computer application      allowed     Medium room
1996  2796812     1               nursing      allowed     Medium room
1997  2796813     2               nursing      allowed     Medium room
1998  2796814     3               nursing      allowed     Medium room
1999  2796815     4               nursing      allowed     Medium room

[2000 rows x 5 columns]

# Q. 강의실 배정하기 pt.2

In [205]:
df = pd.read_csv('C:/codeit/enrolment_3.csv')
df.rename(columns = {'room assignment':'room number'}, inplace = True)

allowed = df['status'] == 'allowed'
course_count = df.loc[allowed, 'course name'].value_counts()
# df 문에 조건 넣을 땐, 무조건 .loc 달아줘야 한다.

aud = list(course_count[course_count >= 80].index)
lar  = list(course_count[(80 > course_count)&(course_count >= 40)].index)
medi = list(course_count[(40 > course_count)&(course_count >= 15)].index)
small = list(course_count[(15 > course_count)&(course_count >= 5)].index)

aud.sort()
lar.sort()
medi.sort()
small.sort()

df.rename(columns = {'room assignment':'room number'})

number = 1
for course in aud:
    df.loc[df['course name']==course, 'room number'] = 'Auditorium-' + str(number)
    number += 1

number = 1
for course in lar:
    df.loc[df['course name']==course, 'room number'] = 'Large-' + str(number)
    number += 1

number = 1
for course in medi:
    df.loc[df['course name']==course, 'room number'] = 'Medium-' + str(number)
    number += 1

number = 1
for course in small:
    df.loc[df['course name']==course, 'room number'] = 'Small-' + str(number)
    number += 1

df.loc[df['status'] ==' not allowed', 'room number']='not assigned'

df


# 쪼렙의 코딩, 대체로 파국이다.

           id  year           course name       status   room number
0     2777729     1               science      allowed  Auditorium-3
1     2777730     2               science      allowed  Auditorium-3
2     2777765     1                  arts      allowed  Auditorium-1
3     2777766     2                  arts      allowed  Auditorium-1
4     2777785     1                   mba      allowed      Small-34
5     2777786     2                   mba      allowed      Small-34
6     2777793     1         mba 2nd shift  not allowed  not assigned
7     2777794     2         mba 2nd shift  not allowed  not assigned
8     2777795     1         mca 2nd shift  not allowed  not assigned
9     2777796     2         mca 2nd shift  not allowed  not assigned
10    2777797     3         mca 2nd shift  not allowed  not assigned
11    2777798     1                  bjmc  not allowed  not assigned
12    2777799     2                  bjmc  not allowed  not assigned
13    2777800     3                  bjmc  not allowed  not assigned
14    2777814     1               history      allowed     Medium-15
15    2777815     2               history      allowed     Medium-15
16    2777837     4             chemistry      allowed      Medium-3
17    2777858     4                botany      allowed      Medium-1
18    2604364     1               history      allowed     Medium-15
19    2604408     3               finance      allowed      Small-24
20    2604407     2               finance      allowed      Small-24
21    2604420     1               physics      allowed     Medium-23
22    2777899     1      computer science      allowed      Medium-8
23    2604365     2               history      allowed     Medium-15
24    2604413     2               english      allowed       Large-2
25    2604406     1               finance      allowed      Small-24
26    2604366     3               history      allowed     Medium-15
27    2604412     1               english      allowed       Large-2
28    2604421     2               physics      allowed     Medium-23
29    2777900     4              commerce  not allowed  Auditorium-2
...       ...   ...                   ...          ...           ...
1970  2796702     1      computer science      allowed      Medium-8
1971  2796703     2      computer science      allowed      Medium-8
1972  2796704     3      computer science      allowed      Medium-8
1973  2796756     1             education      allowed       Large-1
1974  2796757     2             education      allowed       Large-1
1975  2796769     1            management      allowed     Medium-17
1976  2796770     2            management      allowed     Medium-17
1977  2796771     3            management      allowed     Medium-17
1978  2796772     1           music vocal  not allowed  not assigned
1979  2796773     2           music vocal  not allowed  not assigned
1980  2796774     3           music vocal  not allowed  not assigned
1981  2796783     1     political science      allowed      Small-46
1982  2796784     2     political science      allowed      Small-46
1983  2796785     3     political science      allowed      Small-46
1984  2796786     1        computers (ug)  not allowed  not assigned
1985  2796787     2        computers (ug)  not allowed  not assigned
1986  2796788     3        computers (ug)  not allowed  not assigned
1987  2796789     1             economics      allowed     Medium-11
1988  2796790     2             economics      allowed     Medium-11
1989  2796791     3             economics      allowed     Medium-11
1990  2796800     1                 hindi      allowed      Small-27
1991  2796801     2                 hindi      allowed      Small-27
1992  2796802     3                 hindi      allowed      Small-27
1993  2796803     1  computer application      allowed      Medium-7
1994  2796804     2  computer application      allowed      Medium-7
1995  2796805     3  computer application      allowed      Medium-7
1996  2796812     1               nursing      allowed     Medium-22
1997  2796813     2               nursing      allowed     Medium-22
1998  2796814     3               nursing      allowed     Medium-22
1999  2796815     4               nursing      allowed     Medium-22

[2000 rows x 5 columns]

In [207]:
df = pd.read_csv('C:/codeit/enrolment_3.csv')
df.rename(columns = {'room assignment':'room number'}, inplace = True)
auditorium = sorted(df.loc[df['room number'] == 'Auditorium', 'course name'].unique())
large = sorted(df.loc[df['room number'] == 'Large room', 'course name'].unique())
medium = sorted(df.loc[df['room number'] == 'Medium room', 'course name'].unique())
small = sorted(df.loc[df['room number'] == 'Small room', 'course name'].unique())

allowed = df['status']== 'allowed'

number = 1
for course in auditorium:
    df.loc[(df['course name'] == course)&allowed, 'room number'] = 'Auditorium-'+str(number)
    number += 1

number = 1
for course in large:
    df.loc[(df['course name'] == course)&allowed, 'room number'] = 'Large-'+str(number)
    number += 1

number = 1
for course in medium:
    df.loc[(df['course name'] == course)&allowed, 'room number'] = 'Medium-'+str(number)
    number += 1

number = 1
for course in small:
    df.loc[(df['course name'] == course)&allowed, 'room number'] = 'Small-'+str(number)
    number += 1

    
df
# 코드잇 답변

           id  year           course name       status   room number
0     2777729     1               science      allowed  Auditorium-3
1     2777730     2               science      allowed  Auditorium-3
2     2777765     1                  arts      allowed  Auditorium-1
3     2777766     2                  arts      allowed  Auditorium-1
4     2777785     1                   mba      allowed      Small-34
5     2777786     2                   mba      allowed      Small-34
6     2777793     1         mba 2nd shift  not allowed  not assigned
7     2777794     2         mba 2nd shift  not allowed  not assigned
8     2777795     1         mca 2nd shift  not allowed  not assigned
9     2777796     2         mca 2nd shift  not allowed  not assigned
10    2777797     3         mca 2nd shift  not allowed  not assigned
11    2777798     1                  bjmc  not allowed  not assigned
12    2777799     2                  bjmc  not allowed  not assigned
13    2777800     3                  bjmc  not allowed  not assigned
14    2777814     1               history      allowed     Medium-15
15    2777815     2               history      allowed     Medium-15
16    2777837     4             chemistry      allowed      Medium-3
17    2777858     4                botany      allowed      Medium-1
18    2604364     1               history      allowed     Medium-15
19    2604408     3               finance      allowed      Small-24
20    2604407     2               finance      allowed      Small-24
21    2604420     1               physics      allowed     Medium-23
22    2777899     1      computer science      allowed      Medium-8
23    2604365     2               history      allowed     Medium-15
24    2604413     2               english      allowed       Large-2
25    2604406     1               finance      allowed      Small-24
26    2604366     3               history      allowed     Medium-15
27    2604412     1               english      allowed       Large-2
28    2604421     2               physics      allowed     Medium-23
29    2777900     4              commerce  not allowed  not assigned
...       ...   ...                   ...          ...           ...
1970  2796702     1      computer science      allowed      Medium-8
1971  2796703     2      computer science      allowed      Medium-8
1972  2796704     3      computer science      allowed      Medium-8
1973  2796756     1             education      allowed       Large-1
1974  2796757     2             education      allowed       Large-1
1975  2796769     1            management      allowed     Medium-17
1976  2796770     2            management      allowed     Medium-17
1977  2796771     3            management      allowed     Medium-17
1978  2796772     1           music vocal  not allowed  not assigned
1979  2796773     2           music vocal  not allowed  not assigned
1980  2796774     3           music vocal  not allowed  not assigned
1981  2796783     1     political science      allowed      Small-46
1982  2796784     2     political science      allowed      Small-46
1983  2796785     3     political science      allowed      Small-46
1984  2796786     1        computers (ug)  not allowed  not assigned
1985  2796787     2        computers (ug)  not allowed  not assigned
1986  2796788     3        computers (ug)  not allowed  not assigned
1987  2796789     1             economics      allowed     Medium-11
1988  2796790     2             economics      allowed     Medium-11
1989  2796791     3             economics      allowed     Medium-11
1990  2796800     1                 hindi      allowed      Small-27
1991  2796801     2                 hindi      allowed      Small-27
1992  2796802     3                 hindi      allowed      Small-27
1993  2796803     1  computer application      allowed      Medium-7
1994  2796804     2  computer application      allowed      Medium-7
1995  2796805     3  computer application      allowed      Medium-7
1996  2796812     1               nursing      allowed     Medium-22
1997  2796813     2               nursing      allowed     Medium-22
1998  2796814     3               nursing      allowed     Medium-22
1999  2796815     4               nursing      allowed     Medium-22

[2000 rows x 5 columns]